#!/bin/bash

#------------------------------------------------------------------------------------
# Initialize some variables
#------------------------------------------------------------------------------------
SHELL=/sbin/nologin
FTPCONF=/etc/vsftpd
USERNAME=$1
PASSWORD=$2
HOMEDIR=$3

if [ "$USERNAME" == '' ]
	then
		echo $"Enter Username"
		exit 1;
fi

if [ "$PASSWORD" == '' ]
	then
		echo $"Enter password"
		exit 1;
fi

if [ "$HOMEDIR" == '' ]
	then
		echo $"Enter Path"
		exit 1;
fi


if [ -f $FTPCONF/password ];then
    ACCOUNTDB_TOTALLINES=`grep '.' -c $FTPCONF/password`
else
    ACCOUNTDB_TOTALLINES=0
fi

if [ "$ACCOUNTDB_TOTALLINES" != "0" ];then
        while [ $C -lt $ACCOUNTDB_TOTALLINES ]; do
            VALIDUSER=`sed -n -e "$C p" $FTPCONF/password`
            if [ "$USERNAME" == "$VALIDUSER" ];then
                echo 'User Already Exists.'
                exit;
           fi
           let C=$C+2;
        done
    fi

#------------------------------------------------------------------------------------
# Add some presentation :)
#------------------------------------------------------------------------------------
clear;
echo '-------------------------------------------------------------------'
echo " vsftpd -> Virtual Users -> Add Virtual User"
echo '-------------------------------------------------------------------'

yum -y install epel-release libdb4-utils vsftpd

# Check dependencies
PACKISMISSING=""
PACKDEPENDENCIES="vsftpd libdb4-utils"
for i in `echo $PACKDEPENDENCIES`; do
    /bin/rpm -q $i > /dev/null
    if [ "$?" != "0" ];then
        PACKISMISSING="$PACKISMISSING $i"
    fi
done
if [ "$PACKISMISSING" != "" ];then
    echo " ATTENTION: The following package(s) are needed by this script:"
    for i in `echo $PACKISMISSING`; do
        echo "             - $i"
    done
    echo '-------------------------------------------------------------------'
    exit;
fi

echo " Home directory location         : ${HOMEDIR}/$USERNAME "

mkdir -p /etc/vsftpd/user_conf/
touch /etc/vsftpd/user_conf/$USERNAME
#
# Create specific user configuration
#
echo "dirlist_enable=YES
download_enable=YES
local_root=/var/www/$USER
write_enable=YES" > /etc/vsftpd/user_conf/$USERNAME

#
# Update denied_users file
#
if [ "$USERSTATUS" == "y" ];then
    echo $USERNAME >> $FTPCONF/denied_users
else
    sed -i -r -e "/^$USERNAME$/ d" $FTPCONF/denied_users
fi

#Create user
echo $USERNAME | tee /etc/vsftpd/password{,-nocrypt} > /dev/null

#Update password.db file
mypass=$PASSWORD
echo $mypass >> /etc/vsftpd/password-nocrypt
echo $(openssl passwd -crypt $mypass) >> /etc/vsftpd/password
db_load -T -t hash -f $FTPCONF/password $FTPCONF/password.db

# Create ftp virtual user $HOMEDIR
if [ ! -d $HOMEDIR  ];then
    mkdir $HOMEDIR
fi


# Set Permissions
chmod 600 $FTPCONF/password.db
chmod 750 $HOMEDIR

useradd -d $HOMEDIR/$USERNAME -s /sbin/nologin $USERNAME
echo "$USERNAME:$PASSWORD" | /usr/sbin/chpasswd

chown -R $USERNAME:$USERNAME $HOMEDIR


# Restart vsftpd after user addition.
echo '-------------------------------------------------------------------'
systemctl restart vsftpd
echo '-------------------------------------------------------------------'
