#!/bin/bash

#------------------------------------------------------------------------------------
# Initialize some variables
#------------------------------------------------------------------------------------
SHELL=/sbin/nologin
FTPCONF=/etc/vsftpd
USERNAME=$1
PASSWORD=$2
HOMEDIR=$3
ip=$(curl http://checkip.amazonaws.com)

if [ "$USERNAME" == '' ]
	then
		echo $"Enter Username"
		exit 1;
fi

if [ "$PASSWORD" == '' ]
	then
		echo $"Enter password"
		exit 1;
fi

if [ "$HOMEDIR" == '' ]
	then
		echo $"Enter Path"
		exit 1;
fi


if [ -f $FTPCONF/password ];then
    ACCOUNTDB_TOTALLINES=`grep '.' -c $FTPCONF/password`
else
    ACCOUNTDB_TOTALLINES=0
fi

if [ "$ACCOUNTDB_TOTALLINES" != "0" ];then
        while [ $C -lt $ACCOUNTDB_TOTALLINES ]; do
            VALIDUSER=`sed -n -e "$C p" $FTPCONF/password`
            if [ "$USERNAME" == "$VALIDUSER" ];then
                echo 'User Already Exists.'
                exit;
           fi
           let C=$C+2;
        done
fi

yum -y install epel-release vsftpd
yum -y libdb4-utils
mkdir /etc/ssl/private/ && sudo openssl req -x509 -nodes -keyout /etc/ssl/private/vsftpd.pem -out /etc/ssl/private/vsftpd.pem -days 365 -newkey rsa:2048
firewall-cmd --permanent --zone=public --add-service=http
firewall-cmd --permanent --zone=public --add-service=https
firewall-cmd --permanent --zone=public --add-service=ftp
firewall-cmd --permanent --add-port=12000-12100/tcp
firewall-cmd --reload

grep -qxF 'anonymous_enable=NO' $FTPCONF/vsftpd.conf || echo 'anonymous_enable=NO' >> $FTPCONF/vsftpd.conf
grep -qxF 'listen_ipv6=NO' $FTPCONF/vsftpd.conf || echo 'listen_ipv6=NO' >> $FTPCONF/vsftpd.conf
grep -qxF 'listen=YES' $FTPCONF/vsftpd.conf || echo 'listen=YES' >> $FTPCONF/vsftpd.conf
grep -qxF 'pasv_enable=YES' $FTPCONF/vsftpd.conf || echo 'pasv_enable=YES' >> $FTPCONF/vsftpd.conf
grep -qxF 'pasv_min_port=12000' $FTPCONF/vsftpd.conf || echo 'pasv_min_port=12000' >> $FTPCONF/vsftpd.conf
grep -qxF 'pasv_max_port=12100' $FTPCONF/vsftpd.conf || echo 'pasv_max_port=12100' >> $FTPCONF/vsftpd.conf
grep -qxF 'port_enable=YES' $FTPCONF/vsftpd.conf || echo 'port_enable=YES' >> $FTPCONF/vsftpd.conf
grep -qxF 'pasv_addr_resolve=NO' $FTPCONF/vsftpd.conf || echo 'pasv_addr_resolve=NO' >> $FTPCONF/vsftpd.conf
grep -qxF 'pasv_address=$ip' $FTPCONF/vsftpd.conf || echo 'pasv_address=$ip' >> $FTPCONF/vsftpd.conf
grep -qxF 'ssl_enable=YES' $FTPCONF/vsftpd.conf || echo 'ssl_enable=YES' >> $FTPCONF/vsftpd.conf
grep -qxF 'allow_anon_ssl=NO' $FTPCONF/vsftpd.conf || echo 'allow_anon_ssl=NO' >> $FTPCONF/vsftpd.conf
grep -qxF 'force_local_data_ssl=NO' $FTPCONF/vsftpd.conf || echo 'force_local_data_ssl=NO' >> $FTPCONF/vsftpd.conf
grep -qxF 'force_local_logins_ssl=NO' $FTPCONF/vsftpd.conf || echo 'force_local_logins_ssl=NO' >> $FTPCONF/vsftpd.conf
grep -qxF 'ssl_tlsv1=YES' $FTPCONF/vsftpd.conf || echo 'ssl_tlsv1=YES' >> $FTPCONF/vsftpd.conf
grep -qxF 'ssl_sslv2=NO' $FTPCONF/vsftpd.conf || echo 'ssl_sslv2=NO' >> $FTPCONF/vsftpd.conf
grep -qxF 'ssl_sslv3=NO' $FTPCONF/vsftpd.conf || echo 'ssl_sslv3=NO' >> $FTPCONF/vsftpd.conf
grep -qxF 'rsa_cert_file=/etc/ssl/private/vsftpd.pem' $FTPCONF/vsftpd.conf || echo 'rsa_cert_file=/etc/ssl/private/vsftpd.pem' >> $FTPCONF/vsftpd.conf
grep -qxF 'rsa_private_key_file=/etc/ssl/private/vsftpd.pem' $FTPCONF/vsftpd.conf || echo 'rsa_private_key_file=/etc/ssl/private/vsftpd.pem' >> $FTPCONF/vsftpd.conf

echo "dirlist_enable=YES
download_enable=YES
local_root=/var/www/$USER
write_enable=YES" > $FTPCONF/vsftpd.conf

#------------------------------------------------------------------------------------
# Add some presentation :)
#------------------------------------------------------------------------------------

echo '-------------------------------------------------------------------'
echo " vsftpd -> Virtual Users -> Add Virtual User"
echo '-------------------------------------------------------------------'


# Check dependencies
PACKISMISSING=""
PACKDEPENDENCIES="vsftpd libdb4-utils"
for i in `echo $PACKDEPENDENCIES`; do
    /bin/rpm -q $i > /dev/null
    if [ "$?" != "0" ];then
        PACKISMISSING="$PACKISMISSING $i"
    fi
done
if [ "$PACKISMISSING" != "" ];then
    echo " ATTENTION: The following package(s) are needed by this script:"
    for i in `echo $PACKISMISSING`; do
        echo "             - $i"
    done
    echo '-------------------------------------------------------------------'
    exit;
fi

echo " Home directory location         : ${HOMEDIR} "

mkdir -p /etc/vsftpd/user_conf/
touch /etc/vsftpd/user_conf/$USERNAME
#
# Create specific user configuration
#
echo "dirlist_enable=YES
download_enable=YES
local_root=/var/www/$USER
write_enable=YES" > /etc/vsftpd/user_conf/$USERNAME

#
# Update denied_users file
#
if [ "$USERSTATUS" == "y" ];then
    echo $USERNAME >> $FTPCONF/denied_users
else
    sed -i -r -e "/^$USERNAME$/ d" $FTPCONF/denied_users
fi

#Create user
echo $USERNAME | tee /etc/vsftpd/password{,-nocrypt} > /dev/null

#Update password.db file
mypass=$PASSWORD
echo $mypass >> /etc/vsftpd/password-nocrypt
echo $(openssl passwd -crypt $mypass) >> /etc/vsftpd/password
db_load -T -t hash -f $FTPCONF/password $FTPCONF/password.db

# Create ftp virtual user $HOMEDIR
if [ ! -d $HOMEDIR  ];then
    mkdir $HOMEDIR
fi


# Set Permissions
chmod 600 $FTPCONF/password.db
chmod 750 $HOMEDIR

useradd -d $HOMEDIR -s /sbin/nologin $USERNAME
echo "$USERNAME:$PASSWORD" | /usr/sbin/chpasswd

chown -R $USERNAME:$USERNAME $HOMEDIR


# Restart vsftpd after user addition.
echo '-------------------------------------------------------------------'
systemctl restart vsftpd
echo '-------------------------------------------------------------------'
