#!/bin/bash

domain=$1
ftp_user=$2
password=$3
base_dir=/var/www/websites
if [ "$domain" == "" ]; then
    echo "Enter Domain"
    exit
fi
if [ "$ftp_user" == "" ]; then
    echo "Enter FTP User"
    exit
fi
if [ "$password" == "" ]; then
    echo "Enter Password"
    exit
fi
yum install nano -y
cd /usr/local/bin
rm -rf create_domain create_ftp
wget https://github.com/gnakul2001/web_essentials/raw/master/create_domain
wget https://github.com/gnakul2001/web_essentials/raw/master/create_ftp
chmod +x create_domain
chmod +x create_ftp
create_domain create $domain $domain
create_ftp $ftp_user $password $base_dir/$domain
chown -R $ftp_user:$ftp_user $base_dir/$domain
sudo chgrp -R apache $base_dir/$domain/application/storage
sudo chgrp -R apache $base_dir/$domain/application/bootstrap
chmod -R 775 $base_dir/$domain/application/storage
chmod -R 775 $base_dir/$domain/application/bootstrap
echo -e $"Domain: $domain\n FTP User: $ftp_user\n Password: $password\n Domain Dir: $base_dir/$domain"
